# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34eaa84a0a7dfc68ba5f313bf65ba881eccadeea4e27a6cacd2febbe8712fb8c240ec727dc04b5846bb27c7174c1e3d8aba48e932a419955b621f48b6d90e7f8

test:
  secret_key_base: 0efad20c4020debea35921f9500368bb5ff9e9e9f4d914bf96760f9480df79c40f34cc8e772009921ebabb70e3ac181691662200719f5349872b02534ab41d19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
