# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d809a587c774018da743cd0ca38008c38188cd1277d9e8dd2a5448c41625ff6154548e374015f03b2fcec7f996b7be55bbf119d1dbb6bac5f77a3a8e8cd2e5f7

test:
  secret_key_base: 58897f3041fc996bc671ab383386189915c04113a54884a541200ef332fdd96e307a8decfbe8515cdda16ca42581347097cbc0f6d7e58d67d46e1c55cd6f76d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
